baseURL = '/'
languageCode = 'en'
DefaultContentLanguage = "en"
title = 'enlezLab starter'

defaultMarkdownHandler = 'goldmark'
removePathAccents = true

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[permalinks]
  posts = "/:slug/"


[menus]

[[menus.main]]
name = "About"
url = "/about"
weight = "1"

[[menus.main]]
name = "Coaching"
url = "/coaching"
weight = "2"

[[menus.main]]
name = "Contact"
url = "/contact"
weight = "7"


